name: "Lesson 4 - Exercise 1"

on:
    push:
      branches:
        - main
      paths:
        - '.github/workflows/lesson4_exercise1.yaml' # auto-run on changes to this file
    workflow_dispatch:

jobs:
    fetch-api-data:
      runs-on: ubuntu-latest
      steps:
        - name: Save API response to a file
          run: |
            curl https://jsonplaceholder.typicode.com/posts/1 > response.json

            # Count the number of words in the title and body
            title_words_count=$(cat response.json | jq -r '.title' | wc -w | xargs)
            body_words_count=$(cat response.json | jq -r '.body' | wc -w | xargs)

            # Print the word count
            echo "Title word count: $title_words_count"
            echo "Body word count: $body_words_count"

            ## Add your answer below this line
            echo "words in title: $title_words_count" >> $GITHUB_STEP_SUMMARY
            echo "words in body:  $body_words_count" >> $GITHUB_STEP_SUMMARY

    demo-commands:
      runs-on: ubuntu-latest
      steps:
        - name: Demonstrate workflow commands
          run: |
            echo "# Use Markdown!" >> $GITHUB_STEP_SUMMARY
            echo "see GitHub Actions docs about
                [Workflow Commands, Setting an error message](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-error-message)"
                 >> $GITHUB_STEP_SUMMARY
            echo "please inspect the log for details" >> $GITHUB_STEP_SUMMARY

            echo "::group::collapsible log section"
            echo "::debug::Set the Octocat variable"
            echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
            echo "::endgroup::"
        - name: Demonstrate failing step
          run: |
            echo "::error title=ADVICE::Missing semicolon, buddy!"
          continue-on-error: false

    demo-parameters:
        runs-on: ubuntu-latest
        steps:
          - name: Set color to either red or blue randomly
            id: color-selector
            run: |
              if [ $((RANDOM % 2)) -eq 0 ]; then
                echo "SELECTED_COLOR=red" >> "$GITHUB_OUTPUT"
              else
                echo "SELECTED_COLOR=blue" >> "$GITHUB_OUTPUT"
              fi
          - name: Get color
            env:
              SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
            run: |
              echo "The selected color is $SELECTED_COLOR" >> $GITHUB_STEP_SUMMARY
