name: "Lesson 3 - Exercise 1 - Caller" # calls the reusable workflow

on:
    workflow_dispatch:
        inputs:
            message:
                description: "personal message"
                required: true
                type: string

jobs:
    reuseable_workflow_caller:
        uses: thilo20/github-actions/.github/workflows/lesson3_exercise1.yaml@main
        with:
            actor: ${{ inputs.message }}